-- Add new items to the correct categories in the qb-houses/config.lua file:
-- Warning: Some categories are probably already registered by your config. Do not create duplicate categories. (sofas, tables)



sofas = { 
    label = 'Sofas',
    items = {
        { object = 'bzzz_living_sofa_a1',  price = 1000, label = 'Grey Sofa 1' },
        { object = 'bzzz_living_sofa_a2',  price = 1200, label = 'Grey Sofa 2' },
        { object = 'bzzz_living_sofa_a3',  price = 1000, label = 'Black Sofa 1' },
        { object = 'bzzz_living_sofa_a4',  price = 1200, label = 'Black Sofa 2' },
        { object = 'bzzz_living_sofa_a5',  price = 1000, label = 'Brown Sofa 1' },
        { object = 'bzzz_living_sofa_a6',  price = 1200, label = 'Brown Sofa 2' },
        { object = 'bzzz_living_sofa_a7',  price = 1000, label = 'Red Sofa 1' },
        { object = 'bzzz_living_sofa_a8',  price = 1200, label = 'Red Sofa 2' },
        { object = 'bzzz_living_sofa_a9',  price = 1000, label = 'Green Sofa 1' },
        { object = 'bzzz_living_sofa_a10', price = 1200, label = 'Green Sofa 2' },
        { object = 'bzzz_living_sofa_a11', price = 1000, label = 'Blue Sofa 1' },
        { object = 'bzzz_living_sofa_a12', price = 1200, label = 'Blue Sofa 2' },
        { object = 'bzzz_living_sofa_a13', price = 1000, label = 'Purple Sofa 1' },
        { object = 'bzzz_living_sofa_a14', price = 1200, label = 'Purple Sofa 2' },
        { object = 'bzzz_living_sofa_a15', price = 1000, label = 'White Sofa 1' },
        { object = 'bzzz_living_sofa_a16', price = 1200, label = 'White Sofa 2' },
        { object = 'bzzz_living_sofa_b1',  price = 1500, label = 'Grey Corner Sofa' },
        { object = 'bzzz_living_sofa_b2',  price = 1500, label = 'Black Corner Sofa' },
        { object = 'bzzz_living_sofa_b3',  price = 1500, label = 'Brown Corner Sofa' },
        { object = 'bzzz_living_sofa_b4',  price = 1500, label = 'Red Corner Sofa' },
        { object = 'bzzz_living_sofa_b5',  price = 1500, label = 'Green Corner Sofa' },
        { object = 'bzzz_living_sofa_b6',  price = 1500, label = 'Blue Corner Sofa' },
        { object = 'bzzz_living_sofa_b7',  price = 1500, label = 'Purple Corner Sofa' },
        { object = 'bzzz_living_sofa_b8',  price = 1500, label = 'White Corner Sofa' },
        { object = 'bzzz_living_sofa_c1',  price = 1500, label = 'Yellow Modern Sofa' },
        { object = 'bzzz_living_sofa_c2',  price = 1500, label = 'Purple Modern Sofa' },
        { object = 'bzzz_living_sofa_c3',  price = 1500, label = 'Blue Modern Sofa' },
        { object = 'bzzz_living_sofa_c4',  price = 1500, label = 'Green Modern Sofa' },
        { object = 'bzzz_living_sofa_c5',  price = 1500, label = 'Grey Modern Sofa' },
        { object = 'bzzz_living_sofa_c6',  price = 1500, label = 'Red Modern Sofa' },
        { object = 'bzzz_living_sofa_c7',  price = 1500, label = 'Brown Modern Sofa' },
        { object = 'bzzz_living_sofa_c8',  price = 1500, label = 'White Modern Sofa' },
        { object = 'bzzz_living_sofa_d1',  price = 1000, label = 'White Sofa 3' },
        { object = 'bzzz_living_sofa_d2',  price = 1000, label = 'Grey Sofa 3' },
        { object = 'bzzz_living_sofa_d3',  price = 1000, label = 'Red Sofa 3' },
        { object = 'bzzz_living_sofa_d4',  price = 1000, label = 'Purple Sofa 3' },
        { object = 'bzzz_living_sofa_d5',  price = 1000, label = 'Blue Sofa 3' },
        { object = 'bzzz_living_sofa_d6',  price = 1000, label = 'Green Sofa 3' },
        { object = 'bzzz_living_sofa_d7',  price = 1000, label = 'Brown Sofa 3' },
        { object = 'bzzz_living_sofa_d8',  price = 1000, label = 'Black Sofa 3' },
        { object = 'bzzz_living_sofa_e1',  price = 1000, label = 'Grey Sofa 4' },
        { object = 'bzzz_living_sofa_e2',  price = 1000, label = 'Red Sofa 4' },
        { object = 'bzzz_living_sofa_e3',  price = 1000, label = 'Brown Sofa 4' },
        { object = 'bzzz_living_sofa_e4',  price = 1000, label = 'Blue Sofa 4' },
        { object = 'bzzz_living_sofa_f1',  price = 1200, label = 'Red Decorative Sofa 5' },
        { object = 'bzzz_living_sofa_f2',  price = 1200, label = 'Green Decorative Sofa 5' },
        { object = 'bzzz_living_sofa_f3',  price = 1200, label = 'Blue Decorative Sofa 5' },
        { object = 'bzzz_living_sofa_f4',  price = 1200, label = 'Brown Decorative Sofa 5' },
        { object = 'bzzz_living_sofa_g1',  price = 1000, label = 'Grey Sofa 6' },
        { object = 'bzzz_living_sofa_g2',  price = 1200, label = 'Brown Decorative Sofa 6' },
        { object = 'bzzz_living_sofa_g3',  price = 1200, label = 'Red Decorative Sofa 6' },
        { object = 'bzzz_living_sofa_g4',  price = 1200, label = 'Green Decorative Sofa 6' },
        { object = 'bzzz_living_sofa_g5',  price = 1200, label = 'Black Decorative Sofa 6' },
        { object = 'bzzz_living_sofa_g6',  price = 1200, label = 'White Decorative Sofa 6' },
        { object = 'bzzz_living_sofa_h1',  price = 1200, label = 'Brown Decorative Sofa 7' },
        { object = 'bzzz_living_sofa_h2',  price = 1200, label = 'Red Decorative Sofa 7' },
        { object = 'bzzz_living_sofa_h3',  price = 1200, label = 'Green Decorative Sofa 7' },
        { object = 'bzzz_living_sofa_h4',  price = 1200, label = 'Black Decorative Sofa 7' },
        { object = 'bzzz_living_sofa_h5',  price = 1200, label = 'White Decorative Sofa 7' },
    },
},

tables = {
    label = 'Tables',
    items = {
        { object = 'bzzz_living_table_a1', price = 500, label = 'Low Table (Light)' },
        { object = 'bzzz_living_table_a2', price = 500, label = 'Low Table (Dark)' },
        { object = 'bzzz_living_table_a3', price = 500, label = 'Low Table (White)' },
        { object = 'bzzz_living_table_a4', price = 500, label = 'High Table (Light)' },
        { object = 'bzzz_living_table_a5', price = 500, label = 'High Table (Dark)' },
        { object = 'bzzz_living_table_a6', price = 500, label = 'High Table (White)' },
        { object = 'bzzz_living_table_b1', price = 700, label = 'Marble Table' },
        { object = 'bzzz_living_table_b2', price = 700, label = 'Marble Table' },
        { object = 'bzzz_living_table_b3', price = 700, label = 'Marble Table' },
        { object = 'bzzz_living_table_c1', price = 700, label = 'Glass Table 1' },
        { object = 'bzzz_living_table_c2', price = 700, label = 'Glass Table 2' },
        { object = 'bzzz_living_table_c3', price = 700, label = 'Glass Table 3' },
        { object = 'bzzz_living_table_d1', price = 500, label = 'Wood table 1' },
        { object = 'bzzz_living_table_d2', price = 500, label = 'Wood table 2' },
        { object = 'bzzz_living_table_e1', price = 500, label = 'Round Wooden Table (Light)' },
        { object = 'bzzz_living_table_e2', price = 500, label = 'Round Wooden Table (Dark)' },
        { object = 'bzzz_living_table_e3', price = 500, label = 'Round Wooden Table (White)' },
        { object = 'bzzz_living_table_e4', price = 500, label = 'Round Wooden Table (Light)' },
        { object = 'bzzz_living_table_e5', price = 500, label = 'Round Wooden Table (Dark)' },
        { object = 'bzzz_living_table_e6', price = 500, label = 'Round Wooden Table (White)' },
        { object = 'bzzz_living_table_f1', price = 700, label = 'Round Glass Table 1' },
        { object = 'bzzz_living_table_f2', price = 700, label = 'Round Glass Table 2' },
        { object = 'bzzz_living_table_f3', price = 700, label = 'Round Glass Table 3' },
        { object = 'bzzz_living_table_f4', price = 700, label = 'Round Glass Table 4' },
        { object = 'bzzz_living_table_f5', price = 700, label = 'Round Glass Table 5' },
        { object = 'bzzz_living_table_f6', price = 700, label = 'Round Glass Table 6' },
        { object = 'bzzz_living_table_g1', price = 700, label = 'Wood Modern table (Light)' },
        { object = 'bzzz_living_table_g2', price = 700, label = 'Wood Modern table (Black)' },
        { object = 'bzzz_living_table_g3', price = 700, label = 'Wood Modern table (White)' },
        { object = 'bzzz_living_table_g4', price = 700, label = 'Wood Modern table (Dark)' },
        { object = 'bzzz_living_table_h1', price = 700, label = 'Marble Modern table (Light)' },
        { object = 'bzzz_living_table_h2', price = 700, label = 'Marble Modern table (Dark)' },
        { object = 'bzzz_living_table_h3', price = 700, label = 'Marble Modern table (White)' },
        { object = 'bzzz_living_table_i1', price = 700, label = 'Marble Table (White)' },
        { object = 'bzzz_living_table_i2', price = 700, label = 'Marble Table (Grey)' },
        { object = 'bzzz_living_table_i3', price = 700, label = 'Marble Table (Dark)' },
    },
},

bookcases = {
    label = 'Bookcases',
    items = {
        { object = 'bzzz_living_bookcase_a',  price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_a2', price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_a3', price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_b',  price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_b2', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_b3', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_c',  price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_c2', price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_c3', price = 800, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_d',  price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_d2', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_d3', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_e',  price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_e2', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_e3', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_f',  price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_f2', price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_f3', price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_g',  price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_g2', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_g3', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_h',  price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_h2', price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_h3', price = 700, label = 'Empty Bookcase' },
        { object = 'bzzz_living_bookcase_i',  price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_i2', price = 900, label = 'Bookcase with Books' },
        { object = 'bzzz_living_bookcase_i3', price = 900, label = 'Bookcase with Books' },
    },
},

cabinets = {
    label = 'Cabinets',
    items = {
        { object = 'bzzz_living_cabinet_a',  price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_a2', price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_a3', price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_b',  price = 900, label = 'Cabinet with Decorations' },
        { object = 'bzzz_living_cabinet_b2', price = 900, label = 'Cabinet with Decorations' },
        { object = 'bzzz_living_cabinet_b3', price = 900, label = 'Cabinet with Decorations' },
        { object = 'bzzz_living_cabinet_c',  price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_c2', price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_c3', price = 750, label = 'Empty Cabinet' },
        { object = 'bzzz_living_cabinet_d',  price = 900, label = 'Cabinet with Decorations' },
        { object = 'bzzz_living_cabinet_d2', price = 900, label = 'Cabinet with Decorations' },
        { object = 'bzzz_living_cabinet_d3', price = 900, label = 'Cabinet with Decorations' },
    },
},

carpets = {
    label = 'Carpets',
    items = {
        { object = 'bzzz_living_carpet_a',  price = 500, label = 'Green Carpet' },
        { object = 'bzzz_living_carpet_a2', price = 500, label = 'Green Carpet' },
        { object = 'bzzz_living_carpet_a3', price = 500, label = 'Patterned Rug' },
        { object = 'bzzz_living_carpet_b',  price = 500, label = 'Red Carpet' },
        { object = 'bzzz_living_carpet_b2', price = 500, label = 'Red Carpet' },
        { object = 'bzzz_living_carpet_b3', price = 500, label = 'Patterned Rug' },
        { object = 'bzzz_living_carpet_c',  price = 500, label = 'Brown Carpet' },
        { object = 'bzzz_living_carpet_c2', price = 500, label = 'Brown Carpet' },
        { object = 'bzzz_living_carpet_d',  price = 500, label = 'Blue Carpet' },
        { object = 'bzzz_living_carpet_d2', price = 500, label = 'Blue Carpet' },
        { object = 'bzzz_living_carpet_e',  price = 500, label = 'Purple Carpet' },
        { object = 'bzzz_living_carpet_e2', price = 500, label = 'Purple Carpet' },
        { object = 'bzzz_living_carpet_f',  price = 500, label = 'Grey Carpet' },
        { object = 'bzzz_living_carpet_f2', price = 500, label = 'Grey Carpet' },
        { object = 'bzzz_living_carpet_g',  price = 500, label = 'White Carpet' },
        { object = 'bzzz_living_carpet_g2', price = 500, label = 'White Carpet' },
        { object = 'bzzz_living_carpet_h',  price = 500, label = 'Black Carpet' },
        { object = 'bzzz_living_carpet_h2', price = 500, label = 'Black Carpet' },
    },
},

clocks = {
    label = 'Clocks',
    items = {
        { object = 'bzzz_living_clock_a', price = 300, label = 'Clock (Light Wood)' },
        { object = 'bzzz_living_clock_b', price = 300, label = 'Clock (Dark Wood)' },
        { object = 'bzzz_living_clock_c', price = 300, label = 'Clock (White Wood)' },
    },
},

decorations = {
    label = 'Decorations',
    items = {
        { object = 'bzzz_living_decor_a', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_b', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_c', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_d', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_e', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_f', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_g', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_h', price = 100, label = 'Photo frame' },
        { object = 'bzzz_living_decor_i', price = 300, label = 'Decorative pyramid' },
        { object = 'bzzz_living_decor_j', price = 300, label = 'Decorative pyramid' },
        { object = 'bzzz_living_decor_k', price = 300, label = 'Decorative bowl' },
        { object = 'bzzz_living_decor_l', price = 300, label = 'Decorative circle' },
        { object = 'bzzz_living_decor_m', price = 300, label = 'Decorative vase' },
        { object = 'bzzz_living_decor_n', price = 300, label = 'Plant' },
        { object = 'bzzz_living_decor_o', price = 300, label = 'Decorative vase' },
    },
},

fireplaces = {
    label = 'Fireplaces',
    items = {
        { object = 'bzzz_living_fireplace_a',  price = 1200, label = 'Fireplace with fire' },
        { object = 'bzzz_living_fireplace_a2', price = 1200, label = 'Fireplace' },
        { object = 'bzzz_living_fireplace_b',  price = 1200, label = 'Fireplace with fire' },
        { object = 'bzzz_living_fireplace_b2', price = 1200, label = 'Fireplace' },
    },
},

paintings = {
    label = 'Paintings',
    items = {
        { object = 'bzzz_living_painting_a', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_b', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_c', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_d', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_e', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_f', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_g', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_h', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_i', price = 250, label = 'Wall art' },
        { object = 'bzzz_living_painting_j', price = 250, label = 'Wall art' },
    },
},

pillows = {
    label = 'Pillows',
    items = {
        { object = 'bzzz_living_pillow_a',  price = 150, label = 'White Pillow' },
        { object = 'bzzz_living_pillow_a2', price = 150, label = 'White Pillow' },
        { object = 'bzzz_living_pillow_b',  price = 150, label = 'Grey Pillow' },
        { object = 'bzzz_living_pillow_b2', price = 150, label = 'Grey Pillow' },
        { object = 'bzzz_living_pillow_c',  price = 150, label = 'Brown Pillow' },
        { object = 'bzzz_living_pillow_c2', price = 150, label = 'Brown Pillow' },
        { object = 'bzzz_living_pillow_d',  price = 150, label = 'Red Pillow' },
        { object = 'bzzz_living_pillow_d2', price = 150, label = 'Red Pillow' },
        { object = 'bzzz_living_pillow_e',  price = 150, label = 'Green Pillow' },
        { object = 'bzzz_living_pillow_e2', price = 150, label = 'Green Pillow' },
        { object = 'bzzz_living_pillow_f',  price = 150, label = 'Blue Pillow' },
        { object = 'bzzz_living_pillow_f2', price = 150, label = 'Blue Pillow' },
        { object = 'bzzz_living_pillow_g',  price = 150, label = 'Purple Pillow' },
        { object = 'bzzz_living_pillow_g2', price = 150, label = 'Purple Pillow' },
        { object = 'bzzz_living_pillow_h',  price = 150, label = 'Black Pillow' },
        { object = 'bzzz_living_pillow_h2', price = 150, label = 'Black Pillow' },
    },
},

shelves = {
    label = 'Shelves',
    items = {
        { object = 'bzzz_living_shelf_a',  price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_a2', price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_a3', price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_b',  price = 400, label = 'Shelf with Decorations' },
        { object = 'bzzz_living_shelf_b2', price = 400, label = 'Shelf with Decorations' },
        { object = 'bzzz_living_shelf_b3', price = 400, label = 'Shelf with Decorations' },
        { object = 'bzzz_living_shelf_c',  price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_c2', price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_c3', price = 250, label = 'Empty Shelf' },
        { object = 'bzzz_living_shelf_d',  price = 400, label = 'Shelf with Decorations' },
        { object = 'bzzz_living_shelf_d2', price = 400, label = 'Shelf with Decorations' },
        { object = 'bzzz_living_shelf_d3', price = 400, label = 'Shelf with Decorations' },
    },
},

stools = {
    label = 'Stools',
    items = {
        { object = 'bzzz_living_stool_a1',  price = 300, label = 'Grey Stool' },
        { object = 'bzzz_living_stool_a2',  price = 300, label = 'Black Stool' },
        { object = 'bzzz_living_stool_a3',  price = 300, label = 'Brown Stool' },
        { object = 'bzzz_living_stool_a4',  price = 300, label = 'Red Stool' },
        { object = 'bzzz_living_stool_a5',  price = 300, label = 'Green Stool' },
        { object = 'bzzz_living_stool_a6',  price = 300, label = 'Blue Stool' },
        { object = 'bzzz_living_stool_a7',  price = 300, label = 'Purple Stool' },
        { object = 'bzzz_living_stool_a8',  price = 300, label = 'White Stool' },
        { object = 'bzzz_living_stool_a9',  price = 300, label = 'Brown Decorative Stool' },
        { object = 'bzzz_living_stool_a10', price = 300, label = 'Red Decorative Stool' },
        { object = 'bzzz_living_stool_a11', price = 300, label = 'Green Decorative Stool' },
        { object = 'bzzz_living_stool_a12', price = 300, label = 'Black Decorative Stool' },
        { object = 'bzzz_living_stool_a13', price = 300, label = 'White Decorative Stool' },
        { object = 'bzzz_living_stool_b1',  price = 300, label = 'Brown Decorative Stool 2' },
        { object = 'bzzz_living_stool_b2',  price = 300, label = 'Red Decorative Stool 2' },
        { object = 'bzzz_living_stool_b3',  price = 300, label = 'Green Decorative Stool 2' },
        { object = 'bzzz_living_stool_b4',  price = 300, label = 'Black Decorative Stool 2' },
        { object = 'bzzz_living_stool_b5',  price = 300, label = 'White Decorative Stool 2' },
        { object = 'bzzz_living_stool_c1',  price = 300, label = 'White Stool 3' },
        { object = 'bzzz_living_stool_c2',  price = 300, label = 'Grey Stool 3' },
        { object = 'bzzz_living_stool_c3',  price = 300, label = 'Red Stool 3' },
        { object = 'bzzz_living_stool_c4',  price = 300, label = 'Purple Stool 3' },
        { object = 'bzzz_living_stool_c5',  price = 300, label = 'Blue Stool 3' },
        { object = 'bzzz_living_stool_c6',  price = 300, label = 'Green Stool 3' },
        { object = 'bzzz_living_stool_c7',  price = 300, label = 'Brown Stool 3' },
        { object = 'bzzz_living_stool_c8',  price = 300, label = 'Black Stool 3' },
        { object = 'bzzz_living_stool_d1',  price = 300, label = 'Red Decorative Stool 4' },
        { object = 'bzzz_living_stool_d2',  price = 300, label = 'Green Decorative Stool 4' },
        { object = 'bzzz_living_stool_d3',  price = 300, label = 'Blue Decorative Stool 4' },
        { object = 'bzzz_living_stool_d4',  price = 300, label = 'Brown Decorative Stool 4' },
    },
},
