-- Create new categories: "Bookcases", "Cabinets", "Carpets", "Fireplaces", "Paintings", "Pillows", "Stools" or add new items to other categories.
-- Note: Some items are assigned to default categories!!!

Config.FurnitureStores = {
  {
    title = "Ikea",
    Catagories = {"Decorations", "Tables", "Sofas", "Bedroom", "Bookcases", "Cabinets", "Carpets", "Fireplaces", "Paintings", "Pillows", "Stools" }
  },
  {
    title = "Electronics Store",
    Catagories = {"Electronics","Kitchen"}
  },
}



Config.FurnitureCatagories = {
    Bookcases = {
        {name = "bzzz_living_bookcase_a", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_a2", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_a3", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_b", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_b2", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_b3", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_c", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_c2", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_c3", title = "Empty Bookcase", price = 1200},
        {name = "bzzz_living_bookcase_d", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_d2", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_d3", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_e", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_e2", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_e3", title = "Bookcase with Books", price = 1700},
        {name = "bzzz_living_bookcase_f", title = "Empty Bookcase", price = 1000},
        {name = "bzzz_living_bookcase_f2", title = "Empty Bookcase", price = 1000},
        {name = "bzzz_living_bookcase_f3", title = "Empty Bookcase", price = 1000},
        {name = "bzzz_living_bookcase_g", title = "Bookcase with Books", price = 1500},
        {name = "bzzz_living_bookcase_g2", title = "Bookcase with Books", price = 1500},
        {name = "bzzz_living_bookcase_g3", title = "Bookcase with Books", price = 1500},
        {name = "bzzz_living_bookcase_h", title = "Empty Bookcase", price = 900},
        {name = "bzzz_living_bookcase_h2", title = "Empty Bookcase", price = 900},
        {name = "bzzz_living_bookcase_h3", title = "Empty Bookcase", price = 900},
        {name = "bzzz_living_bookcase_i", title = "Bookcase with Books", price = 1400},
        {name = "bzzz_living_bookcase_i2", title = "Bookcase with Books", price = 1400},
        {name = "bzzz_living_bookcase_i3", title = "Bookcase with Books", price = 1400},
    },

    Cabinets = {
        {name = "bzzz_living_cabinet_a", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_a2", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_a3", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_b", title = "Cabinet with Decorations", price = 1300},
        {name = "bzzz_living_cabinet_b2", title = "Cabinet with Decorations", price = 1300},
        {name = "bzzz_living_cabinet_b3", title = "Cabinet with Decorations", price = 1300},
        {name = "bzzz_living_cabinet_c", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_c2", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_c3", title = "Empty Cabinet", price = 1000},
        {name = "bzzz_living_cabinet_d", title = "Cabinet with Decorations", price = 1300},
        {name = "bzzz_living_cabinet_d2", title = "Cabinet with Decorations", price = 1300},
        {name = "bzzz_living_cabinet_d3", title = "Cabinet with Decorations", price = 1300},
    },

    Carpets = {
        {name = "bzzz_living_carpet_a", title = "Green Carpet", price = 500},
        {name = "bzzz_living_carpet_a2", title = "Green Carpet", price = 500},
        {name = "bzzz_living_carpet_a3", title = "Patterned Rug", price = 500},
        {name = "bzzz_living_carpet_b", title = "Red Carpet", price = 500},
        {name = "bzzz_living_carpet_b2", title = "Red Carpet", price = 500},
        {name = "bzzz_living_carpet_b3", title = "Patterned Rug", price = 500},
        {name = "bzzz_living_carpet_c", title = "Brown Carpet", price = 500},
        {name = "bzzz_living_carpet_c2", title = "Brown Carpet", price = 500},
        {name = "bzzz_living_carpet_d", title = "Blue Carpet", price = 500},
        {name = "bzzz_living_carpet_d2", title = "Blue Carpet", price = 500},
        {name = "bzzz_living_carpet_e", title = "Purple Carpet", price = 500},
        {name = "bzzz_living_carpet_e2", title = "Purple Carpet", price = 500},
        {name = "bzzz_living_carpet_f", title = "Grey Carpet", price = 500},
        {name = "bzzz_living_carpet_f2", title = "Grey Carpet", price = 500},
        {name = "bzzz_living_carpet_g", title = "White Carpet", price = 500},
        {name = "bzzz_living_carpet_g2", title = "White Carpet", price = 500},
        {name = "bzzz_living_carpet_h", title = "Black Carpet", price = 500},
        {name = "bzzz_living_carpet_h2", title = "Black Carpet", price = 500},
    },

    Clocks = {
        {name = "bzzz_living_clock_a", title = "Clock (Light Wood)", price = 500},
        {name = "bzzz_living_clock_b", title = "Clock (Dark Wood)", price = 500},
        {name = "bzzz_living_clock_c", title = "Clock (White Wood)", price = 500},
    },

    Decorations = {
        {name = "bzzz_living_decor_a", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_b", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_c", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_d", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_e", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_f", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_g", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_h", title = "Photo frame", price = 50},
        {name = "bzzz_living_decor_i", title = "Decorative pyramid", price = 300},
        {name = "bzzz_living_decor_j", title = "Decorative pyramid", price = 300},
        {name = "bzzz_living_decor_k", title = "Decorative bowl", price = 300},
        {name = "bzzz_living_decor_l", title = "Decorative circle", price = 300},
        {name = "bzzz_living_decor_m", title = "Decorative vase", price = 300},
        {name = "bzzz_living_decor_n", title = "Plant", price = 200},
        {name = "bzzz_living_decor_o", title = "Decorative vase", price = 300},
    },

    Fireplaces = {
        {name = "bzzz_living_fireplace_a", title = "Fireplace with fire", price = 1500},
        {name = "bzzz_living_fireplace_a2", title = "Fireplace", price = 1500},
        {name = "bzzz_living_fireplace_b", title = "Fireplace with fire", price = 1500},
        {name = "bzzz_living_fireplace_b2", title = "Fireplace", price = 1500},
    },

    Paintings = {
        {name = "bzzz_living_painting_a", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_b", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_c", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_d", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_e", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_f", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_g", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_h", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_i", title = "Wall art", price = 250},
        {name = "bzzz_living_painting_j", title = "Wall art", price = 250},
    },

    Pillows = {
        {name = "bzzz_living_pillow_a", title = "White Pillow", price = 250},
        {name = "bzzz_living_pillow_a2", title = "White Pillow", price = 250},
        {name = "bzzz_living_pillow_b", title = "Grey Pillow", price = 250},
        {name = "bzzz_living_pillow_b2", title = "Grey Pillow", price = 250},
        {name = "bzzz_living_pillow_c", title = "Brown Pillow", price = 250},
        {name = "bzzz_living_pillow_c2", title = "Brown Pillow", price = 250},
        {name = "bzzz_living_pillow_d", title = "Red Pillow", price = 250},
        {name = "bzzz_living_pillow_d2", title = "Red Pillow", price = 250},
        {name = "bzzz_living_pillow_e", title = "Green Pillow", price = 250},
        {name = "bzzz_living_pillow_e2", title = "Green Pillow", price = 250},
        {name = "bzzz_living_pillow_f", title = "Blue Pillow", price = 250},
        {name = "bzzz_living_pillow_f2", title = "Blue Pillow", price = 250},
        {name = "bzzz_living_pillow_g", title = "Purple Pillow", price = 250},
        {name = "bzzz_living_pillow_g2", title = "Purple Pillow", price = 250},
        {name = "bzzz_living_pillow_h", title = "Black Pillow", price = 250},
        {name = "bzzz_living_pillow_h2", title = "Black Pillow", price = 250},
    },

    Shelves = {
        {name = "bzzz_living_shelf_a", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_a2", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_a3", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_b", title = "Shelf with Decorations", price = 500},
        {name = "bzzz_living_shelf_b2", title = "Shelf with Decorations", price = 500},
        {name = "bzzz_living_shelf_b3", title = "Shelf with Decorations", price = 500},
        {name = "bzzz_living_shelf_c", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_c2", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_c3", title = "Empty Shelf", price = 200},
        {name = "bzzz_living_shelf_d", title = "Shelf with Decorations", price = 500},
        {name = "bzzz_living_shelf_d2", title = "Shelf with Decorations", price = 500},
        {name = "bzzz_living_shelf_d3", title = "Shelf with Decorations", price = 500},
    },

    Sofas = {
        {name = "bzzz_living_sofa_a1", title = "Grey Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a2", title = "Grey Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a3", title = "Black Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a4", title = "Black Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a5", title = "Brown Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a6", title = "Brown Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a7", title = "Red Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a8", title = "Red Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a9", title = "Green Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a10", title = "Green Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a11", title = "Blue Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a12", title = "Blue Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a13", title = "Purple Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a14", title = "Purple Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_a15", title = "White Sofa 1", price = 1500},
        {name = "bzzz_living_sofa_a16", title = "White Sofa 2", price = 1800},
        {name = "bzzz_living_sofa_b1", title = "Grey Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b2", title = "Black Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b3", title = "Brown Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b4", title = "Red Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b5", title = "Green Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b6", title = "Blue Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b7", title = "Purple Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_b8", title = "White Corner Sofa", price = 1800},
        {name = "bzzz_living_sofa_c1", title = "Yellow Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c2", title = "Purple Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c3", title = "Blue Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c4", title = "Green Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c5", title = "Grey Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c6", title = "Red Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c7", title = "Brown Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_c8", title = "White Modern Sofa", price = 2000},
        {name = "bzzz_living_sofa_d1", title = "White Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d2", title = "Grey Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d3", title = "Red Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d4", title = "Purple Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d5", title = "Blue Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d6", title = "Green Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d7", title = "Brown Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_d8", title = "Black Sofa 3", price = 1800},
        {name = "bzzz_living_sofa_e1", title = "Grey Sofa 4", price = 1800},
        {name = "bzzz_living_sofa_e2", title = "Red Sofa 4", price = 1800},
        {name = "bzzz_living_sofa_e3", title = "Brown Sofa 4", price = 1800},
        {name = "bzzz_living_sofa_e4", title = "Blue Sofa 4", price = 1800},
        {name = "bzzz_living_sofa_f1", title = "Red Decorative Sofa 5", price = 1800},
        {name = "bzzz_living_sofa_f2", title = "Green Decorative Sofa 5", price = 1800},
        {name = "bzzz_living_sofa_f3", title = "Blue Decorative Sofa 5", price = 1800},
        {name = "bzzz_living_sofa_f4", title = "Brown Decorative Sofa 5", price = 1800},
        {name = "bzzz_living_sofa_g1", title = "Grey Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_g2", title = "Brown Decorative Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_g3", title = "Red Decorative Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_g4", title = "Green Decorative Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_g5", title = "Black Decorative Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_g6", title = "White Decorative Sofa 6", price = 1800},
        {name = "bzzz_living_sofa_h1", title = "Brown Decorative Sofa 7", price = 1800},
        {name = "bzzz_living_sofa_h2", title = "Red Decorative Sofa 7", price = 1800},
        {name = "bzzz_living_sofa_h3", title = "Green Decorative Sofa 7", price = 1800},
        {name = "bzzz_living_sofa_h4", title = "Black Decorative Sofa 7", price = 1800},
        {name = "bzzz_living_sofa_h5", title = "White Decorative Sofa 7", price = 1800},
    },

    Stools = {
        {name = "bzzz_living_stool_a1", title = "Grey Stool", price = 400},
        {name = "bzzz_living_stool_a2", title = "Black Stool", price = 400},
        {name = "bzzz_living_stool_a3", title = "Brown Stool", price = 400},
        {name = "bzzz_living_stool_a4", title = "Red Stool", price = 400},
        {name = "bzzz_living_stool_a5", title = "Green Stool", price = 400},
        {name = "bzzz_living_stool_a6", title = "Blue Stool", price = 400},
        {name = "bzzz_living_stool_a7", title = "Purple Stool", price = 400},
        {name = "bzzz_living_stool_a8", title = "White Stool", price = 400},
        {name = "bzzz_living_stool_a9", title = "Brown Decorative Stool", price = 400},
        {name = "bzzz_living_stool_a10", title = "Red Decorative Stool", price = 400},
        {name = "bzzz_living_stool_a11", title = "Green Decorative Stool", price = 400},
        {name = "bzzz_living_stool_a12", title = "Black Decorative Stool", price = 400},
        {name = "bzzz_living_stool_a13", title = "White Decorative Stool", price = 400},
        {name = "bzzz_living_stool_b1", title = "Brown Decorative Stool 2", price = 400},
        {name = "bzzz_living_stool_b2", title = "Red Decorative Stool 2", price = 400},
        {name = "bzzz_living_stool_b3", title = "Green Decorative Stool 2", price = 400},
        {name = "bzzz_living_stool_b4", title = "Black Decorative Stool 2", price = 400},
        {name = "bzzz_living_stool_b5", title = "White Decorative Stool 2", price = 400},
        {name = "bzzz_living_stool_c1", title = "White Stool 3", price = 400},
        {name = "bzzz_living_stool_c2", title = "Grey Stool 3", price = 400},
        {name = "bzzz_living_stool_c3", title = "Red Stool 3", price = 400},
        {name = "bzzz_living_stool_c4", title = "Purple Stool 3", price = 400},
        {name = "bzzz_living_stool_c5", title = "Blue Stool 3", price = 400},
        {name = "bzzz_living_stool_c6", title = "Green Stool 3", price = 400},
        {name = "bzzz_living_stool_c7", title = "Brown Stool 3", price = 400},
        {name = "bzzz_living_stool_c8", title = "Black Stool 3", price = 400},
        {name = "bzzz_living_stool_d1", title = "Red Decorative Stool 4", price = 400},
        {name = "bzzz_living_stool_d2", title = "Green Decorative Stool 4", price = 400},
        {name = "bzzz_living_stool_d3", title = "Blue Decorative Stool 4", price = 400},
        {name = "bzzz_living_stool_d4", title = "Brown Decorative Stool 4", price = 400},
    },

    Tables = {
        {name = "bzzz_living_table_a1", title = "Low Table (Light)", price = 800},
        {name = "bzzz_living_table_a2", title = "Low Table (Dark)", price = 800},
        {name = "bzzz_living_table_a3", title = "Low Table (White)", price = 800},
        {name = "bzzz_living_table_a4", title = "High Table (Light)", price = 800},
        {name = "bzzz_living_table_a5", title = "High Table (Dark)", price = 800},
        {name = "bzzz_living_table_a6", title = "High Table (White)", price = 800},
        {name = "bzzz_living_table_b1", title = "Marble Table", price = 800},
        {name = "bzzz_living_table_b2", title = "Marble Table", price = 800},
        {name = "bzzz_living_table_b3", title = "Marble Table", price = 800},
        {name = "bzzz_living_table_c1", title = "Glass Table 1", price = 800},
        {name = "bzzz_living_table_c2", title = "Glass Table 2", price = 800},
        {name = "bzzz_living_table_c3", title = "Glass Table 3", price = 800},
        {name = "bzzz_living_table_d1", title = "Wood table 1", price = 800},
        {name = "bzzz_living_table_d2", title = "Wood table 2", price = 800},
        {name = "bzzz_living_table_e1", title = "Round Wooden Table (Light)", price = 800},
        {name = "bzzz_living_table_e2", title = "Round Wooden Table (Dark)", price = 800},
        {name = "bzzz_living_table_e3", title = "Round Wooden Table (White)", price = 800},
        {name = "bzzz_living_table_e4", title = "Round Wooden Table (Light)", price = 800},
        {name = "bzzz_living_table_e5", title = "Round Wooden Table (Dark)", price = 800},
        {name = "bzzz_living_table_e6", title = "Round Wooden Table (White)", price = 800},
        {name = "bzzz_living_table_f1", title = "Round Glass Table 1", price = 800},
        {name = "bzzz_living_table_f2", title = "Round Glass Table 2", price = 800},
        {name = "bzzz_living_table_f3", title = "Round Glass Table 3", price = 800},
        {name = "bzzz_living_table_f4", title = "Round Glass Table 4", price = 800},
        {name = "bzzz_living_table_f5", title = "Round Glass Table 5", price = 800},
        {name = "bzzz_living_table_f6", title = "Round Glass Table 6", price = 800},
        {name = "bzzz_living_table_g1", title = "Wood Modern table (Light)", price = 800},
        {name = "bzzz_living_table_g2", title = "Wood Modern table (Black)", price = 800},
        {name = "bzzz_living_table_g3", title = "Wood Modern table (White)", price = 800},
        {name = "bzzz_living_table_g4", title = "Wood Modern table (Dark)", price = 800},
        {name = "bzzz_living_table_h1", title = "Marble Modern table (Light)", price = 800},
        {name = "bzzz_living_table_h2", title = "Marble Modern table (Dark)", price = 800},
        {name = "bzzz_living_table_h3", title = "Marble Modern table (White)", price = 800},
        {name = "bzzz_living_table_i1", title = "Marble Table (White)", price = 800},
        {name = "bzzz_living_table_i2", title = "Marble Table (Grey)", price = 800},
        {name = "bzzz_living_table_i3", title = "Marble Table (Dark)", price = 800},
    },

}
